---
title: "1. Введение"
output: html_document
---

```{r, echo = FALSE}
setwd("D:/GITHUB/rlang_manual_ru/")
```

R является системой для статистических вычислений и создания графики, предоставляющей, помимо прочего, язык программирования, высокоуровневую графику, интерфейсы к другим языкам и средства отладки кода. Это руководство описывает язык R.

R является диалектом языка S, созданного в 1980-х и с тех пор широко используемого в статистическом сообществе. Его главный разработчик, Джон М. Чемберс, был награжден ACM Software Systems Award в 1998 г.

Синтаксис языка имеет поверхностное сходство с C, но семантика является вариантом ФЯП (функционального языка программирования), схожего с LISP и APL. В частности, это позволяет осуществлять «вычисления на языке», что, в свою очередь, позволяет писать функции, принимающие на вход выражения. Иногда это очень полезно для статистического моделирования и создания графики.

Можно довольно далеко зайти, используя R в интерактивном режиме, выполняя простые выражения в командной строке. Некоторые пользователи могут никогда не продвинуться дальше этого уровня; другие захотят писать свои собственные функции – либо для систематизации повторяющейся работы, либо с целью создания дополнительных пакетов, реализующих новую функциональность.

Целью данного руководства является описание языка как такового. А именно: объектов, с которыми он работает, и особенностей процесса вычисления выражений, которые полезно знать при написании функций. Основные подсистемы для специфических задач, таких как создание графики, в этом руководстве описаны лишь кратко и будут документированы отдельно.

Хотя большая часть текста будет в равной степени применима и к S, есть также некоторые существенные различия, поэтому мы должны будем сконцентрироваться на описании R, чтобы не сбивать с толку.

В конструкции языка содержится ряд тонкостей и подводных камней, которые могут удивить пользователя. Причиной большинства из них являются соображения непротиворечивости на более глубоком уровне, и это будет нами объясняться. Также есть ряд оптимальных решений и полезных идиом, позволяющих пользователю лаконично выражать довольно сложные операции. Многие из них станут естественными после ознакомления с основополагающими концепциями. Иногда существует несколько способов выполнения задачи, но некоторые техники будут зависеть от реализации языка, а другие будут работать на более высоком уровне абстракции. В таких случаях мы будем указывать предпочтительные способы.

Предполагается некоторое знакомство с R. Это не введение, а скорее справочное руководство для программистов. Другие руководства содержат дополнительную информацию, в частности, раздел «Предисловие» во «Введении в R» содержит введение в язык R, а раздел «Система и интерфейсы к другим языкам» руководства «Написание расширений для R» объясняет, как расширить возможности R с использованием скомпилированного кода.