---
title: "2. Объекты"
output: html_document
---

```{r, echo = FALSE}
setwd("D:/GITHUB/rlang_manual_ru/")
```

В каждом компьютерном языке переменные обеспечивают средства доступа к данным, хранящимся в памяти. R не обеспечивает непосредственного доступа к памяти компьютера, а скорее предоставляет ряд
специализированных структур данных, к которым мы будем обращаться как к объектам. Обращение к этим объектам происходит посредством символов (symbol; использован наиболее буквальный перевод – прим. пер.) или переменных (variable). Тем не менее, в R символы сами по себе являются объектами, и с ними можно совершать те же действия, что и с другими объектами. Это отличает R от многих других языков и приводит к далеко идущим последствиям.
В этой главе мы приводим предварительные описания различных структур данных, представленных в R. Более подробное обсуждение многих из них можно найти в последующих главах. Специальная функция **typeof** возвращает *тип* объекта R. Обратите внимание, что в коде на C, лежащем в основе R, все объекты являются указателями на структуру с типом (typedef) **SEXPREC**; разные типы данных R представлены в C с помощью **SEXPTYPE**, определяющего, как используется информация из разных частей структуры.
Следующая таблица описывает возможные значения, возвращаемые функцией **typeof**, и чем они являются.
